[project]
name = "tagging"
version = "0.9.3"
description = "Default template for PDM package"
authors = [
    {name = "Trey Peacock", email = "git@treypeacock.com"},
]
dependencies = []
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
