# example 2: on merge to master from pull request (recommended)
name: Main Release PR
on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        branch: staging
        body: ${{github.event.release.name}} Release Deployment
        base: main
        reviewers: tpeacock19
        labels: deploy release
